{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "router_id",
    "query": {
     "query": "label_values(cpu_usage,router_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "memoryUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "memory_usage{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpuUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cpu_usage{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "packetsIn/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "in_packet_rate_pps{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inPacketBytes/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "in_packet_rate_bps{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outPacketBytes/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "out_packet_rate_bps{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "packetsOut/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "out_current_packets{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inPacketDrops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "in_packet_drops{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outPacketDrops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "out_packet_drops{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errorsIn",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "in_errors{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errorsOut",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "out_errors{router_id=\"$router_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}